name: Deploy to ConoHa WING (smoke test)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello (YAML sanity check)
        run: echo "YAML OK"
