name: PokecaTopScraper

on:
  schedule:
    - cron: '0 23 * * *'  # JST 8:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      GSHEET_JSON: ${{ secrets.GSHEET_JSON }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run top scraper
        run: python pokeca_to_spreadsheet.py
