name: Scrape YK Oripa

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install

      - name: Run YK Oripa scraper
        env:
          GSHEET_JSON: ${{ secrets.GSHEET_JSON }}
          SPREADSHEET_URL: ${{ secrets.SPREADSHEET_URL }}
        run: python yk_oripa_scraper.py

      - name: Upload debug HTML
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: yk_oripa_debug
          path: yk_oripa_debug.html
