name: Pokeca Banner Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前9時 JST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright gspread google-auth
          playwright install chromium

      - name: Run scraper
        env:
          GSHEET_JSON: ${{ secrets.GSHEET_JSON }}
          SPREADSHEET_URL: ${{ secrets.SPREADSHEET_URL }}
        run: python pokeca_banner_scraper.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scraped-banners
          path: credentials.json
