name: Scrape Pokepa365 to WordPress

on:
  schedule:
    - cron: "0 */3 * * *"  # 6時間ごとに自動実行
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install --with-deps chromium

      - name: Scrape and post to WordPress
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASS: ${{ secrets.WP_APP_PASS }}
        run: |
          python scrape_pokepa365_to_wp.py
