name: Scrape Black Gacha

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run scraper
        env:
          GSHEET_JSON: ${{ secrets.GSHEET_JSON }}
          SPREADSHEET_URL: ${{ secrets.SPREADSHEET_URL }}
        run: python blackgacha_scraper.py

      - name: Upload debug HTML
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: blackgacha_debug
          path: blackgacha_debug.html
