name: Scrape Orikuji with Playwright

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  # 3時間ごとに実行

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install

      - name: Run Orikuji scraper
        env:
          GSHEET_JSON: ${{ secrets.GSHEET_JSON }}
        run: python orikuji_scraper.py

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@7f6cfc3f6b61a7cf1189872ae32db3a0c5089ef2  # ← SHA固定（v3.1.0）
        with:
          name: orikuji_debug
          path: |
            page_debug.html
            debug.png
