name: Scrape Kagura TCG

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  # 3時間ごとに実行

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install  # Python Playwright 用ブラウザをDL

      - name: Run scraper
        env:
          GSHEET_JSON: ${{ secrets.GSHEET_JSON }}
          SPREADSHEET_URL: ${{ secrets.SPREADSHEET_URL }}
        run: python kagura_tcg_scraper.py

      - name: Upload debug HTML
        if: always()  # ← ここを必ず実行に変更
        uses: actions/upload-artifact@v4
        with:
          name: kagura_debug
          path: kagura_debug.html
